//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcResume.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeDbEntities : DbContext
    {
        public ResumeDbEntities()
            : base("name=ResumeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAbout> TblAbouts { get; set; }
        public virtual DbSet<TblAdmin> TblAdmins { get; set; }
        public virtual DbSet<TblCertification> TblCertifications { get; set; }
        public virtual DbSet<TblContact> TblContacts { get; set; }
        public virtual DbSet<TblEducation> TblEducations { get; set; }
        public virtual DbSet<TblExperience> TblExperiences { get; set; }
        public virtual DbSet<TblInterest> TblInterests { get; set; }
        public virtual DbSet<TblSkill> TblSkills { get; set; }
    }
}
